### PR TITLE
March Design Updates

### PR DESCRIPTION
**Pull request by lemillermicrosoft**
Updates for March.

- Show up to 3 predictions with ability to collapse to single prediction on tap.
- Button to select image from gallery and close.
- Button to flip camera selection
- Updated branding icons
- Add Lobe model versioning support
- Design polish

https://user-images.githubusercontent.com/35783676/112401444-c7005380-8cc7-11eb-84e0-72c383d7da5a.mov

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Lee, the only thing I'd say:

The design has the (x) button on the right, and the gallery icon on the left, so you can open the gallery and substitute the image without having to (x) -> (open gallery).

Other than that, the spring bars animation (for the future).

And this is great!

**Review by RamonGilabert — APPROVED** [review]
Added a comment above.

**Comment by lemillermicrosoft** [comment]
> Lee, the only thing I'd say:
> 
> The design has the (x) button on the right, and the gallery icon on the left, so you can open the gallery and substitute the image without having to (x) -> (open gallery).
> 
> Other than that, the spring bars animation (for the future).
> 
> And this is great!

Moved the button and ensured gallery button remains visible.

**Review by mbeissinger — APPROVED** [review]
The icons for gallery/camera switcher/close are a bit fuzzy on the pixel 3 -- might need higher resolution asset or svg

**Comment by lemillermicrosoft** [comment]
> The icons for gallery/camera switcher/close are a bit fuzzy on the pixel 3 -- might need higher resolution asset or svg

Good call -- Ramon had originally sent svgs -- i've switched to using those. Looks good on emulator and my duo. Let me know if they still seem fuzzy after this change.

**Pull request merged**
